insurance_fraud_webapp/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Custom Paths
    path('', 
        include(('main_app.urls', 'main_app'), 
        namespace='home')),

    path('todo_riesgo/',
        include(('main_app.urls','main_app'),
        namespace='all_risk')),

    path('soat/',
        include(('main_app.urls','main_app'),
        namespace='soat')),
    
] 

main_app/urls.py
""" 
    main_app module url management
"""

from django.urls import path
from main_app import views

urlpatterns =  [
    path(
        route='',
        view=views.home,
        name='home'
    ),

    path(
        route='1',
        view=views.all_risk_1,
        name='1'
    ),

    path(
        route='2',
        view=views.all_risk_2,
        name='2'
    ),

    path(
        route='3',
        view=views.all_risk_3,
        name='3'
    ),

    path(
        route='4',
        view=views.all_risk_4,
        name='4'
    ),

    path(
        route='s1',
        view=views.soat_1,
        name='s1'
    ),

    path(
        route='s2',
        view=views.soat_2,
        name='s2'
    ),

]

main_app/models.py
from django.db import models

# Create your models here.

class Parameter(models.Model):
    """
        Class of parámeters
    """
    parameter_key = models.CharField(max_length = 20, null = False, blank = False, verbose_name = 'Llave Parametro')
    parameter_value = models.CharField(max_length = 50, null = False, blank = False, verbose_name = 'Valor Parametro')
    parameter_verbose = models.CharField(max_length = 50, null = False, blank = False, verbose_name = 'Valor para Mostrar')


    class Meta():
        """
            Parameter subclass to set meta information in Parameter
        """
        verbose_name = 'Parametro'
        verbose_name_plural = 'Parametros'

    
    def __str__(self):
        """
            ToString method from Parameter Class
        """
        return ("{} -> {}".format(self.parameter_key, self.parameter_value))

main_app/views.py
# Django libraries
from typing import NewType
from django.shortcuts import render, resolve_url

# Utils functions
from .utils import getDataForModel 
from .utils import load_model
from .utils import get_linear_plot
from .utils import get_seftorganized_plot
from .utils import load_frequencies
from .utils import load_scores
from .utils import load_soat_kmeans
from .utils import get_webapp_parameters
from .utils import load_model_IT2
from .utils import get_3d_freq_plot
from .utils import search_client
from .utils import all_risk_form_data
from .utils import getDataForModel_IT2
from .utils import get_threshold_hist_plot
from .utils import load_dataframe_weight
from .utils import soat_transforms
from .utils import reorder
from .utils import calculate_soat_risk
from .utils import load_dataframe_clusters

from .data_structures import CLIENT_NO_FOUND
from .data_structures import CLIENT_FOUND
from .data_structures import POINT_CALCULATED
from .data_structures import SOAT_DISTANCE
from .data_structures import SOAT_RISK

def home(request):
    """
        View to generate HTML Template respose to URL <IP>:<PORT>/
        @var request: HTTML REQUEST
    """
    return render(request, 'main_app/index.html')


def all_risk_1(request):
    """
        View to generate HTML Template respose to URL <IP>:<PORT>/todo_riesgo/1
        @var request: HTTML REQUEST
    """
    som_2 = load_model()

    data = {}
    point = None

    if request.method == 'POST':
        test_val = getDataForModel(
            SEXO_ASEGURADO  = request.POST['sex_insured'],
            CODIGO_MUNICIPIO  = request.POST['city_policy'],
            DEPARTAMENTO_RIESGO  = request.POST['state_policy'],
            SEXO_CONDUCTOR  = request.POST['gender_sinister'],
            NUMERO_ENDOSO  = request.POST['code_policy'],
            MARCA_VEHICULO  = request.POST['brand_vehicle'],
            LINEA  = request.POST['line_vehicle'],
            MODELO  = request.POST['model_vehicle'],
            COD_USO  = request.POST['use_policy'],
            COD_TIPO  = request.POST['type_policy'],
            VALOR_ASEGURADO_VEHICULO  = request.POST['amount_policy'],
            VALOR_ASEGURADO_ACCESORIOS  = request.POST['amount_a_policy'],
            CILINDRADA  = request.POST['cylinder_vehicle'],
            TIPO_VEHICULO  = request.POST['type_vehicle'],
            ALTURA_POLIZA  = request.POST['height_policy'],
            CANAL_POLIZA  = request.POST['channel_policy'],
            TOMADOR_ASEGURADO_IGUAL_POLIZA  = request.POST['taken_policy'],
            RECLAMOS_ANTERIORES  = request.POST['claims_sinister'],
            EDAD_CONDUCTOR  = request.POST['age_sinister'],
            FECHA_EMISION_ENDOSO_DIAS  = request.POST['date_policy'],
            CODIGO_SUBPRODUCTO  = request.POST['subproduct_policy'],
            DEPARTAMENTO_SINIESTRO  = request.POST['state_sinister'],
            CODIGO_COBERTURA_FRECUENTE  = request.POST['covert_policy'],
            CANT_COBERTURAS_INVOLUCRADAS  = request.POST['involved_policy'],
            CODIGO_CONCEPTO_RESERVA  = request.POST['concept_policy'],
            ESTADO_SINIESTRO_CALCULADO  = request.POST['stage_sinister'],
            INCURRIDO  = request.POST['incurred_sinister'],
            FECHA_MOV_MAX_DIAS  = request.POST['date_sinister'],
            TOMADOR_ASEGURADO_IGUAL_SINIESTRO  = request.POST['taker_a_sinister'],
            TOMADOR_BENEFICIARIO_IGUAL_SINIESTRO  = request.POST['taker_b_sinister'],
            ASEGURADO_BENEFICIARIO_IGUAL_SINIESTRO  = request.POST['insured_sinister'],
            CODIGO_MUNICIPIO_SINIESTRO  = request.POST['city_sinister'],
            TOTAL_INVOLUCRADOS  = request.POST['involved_sinister'],
            DIFF_AVISO_SINIESTRO  = request.POST['annon_sinister'],
            DIFF_INICIO_ENDOSO_SINIESTRO  = request.POST['start_sinister'],
            DIFF_FIN_ENDOSO_SINIESTRO  = request.POST['end_sinister'],
            MUNICIPIO_SINIESTRO_POLIZA_IGUAL  = request.POST['town_sinister'],
            ESTADO_CIVIL  = request.POST['civil_insured'],
            VINCULACION_LABORAL  = request.POST['job_insured'],
            EGRESOS  = request.POST['expenses_insured'],
            INGRESOS  = request.POST['income_insured'],
            VALOR_ACTIVO  = request.POST['assets_insured'],
            VALOR_PASIVO  = request.POST['passives_insured'],
            VALOR_PATRIMONIO  = request.POST['heritage_insured'],
            CODIGO_CIIU  = request.POST['city_insured'],
            ACIERTA_PLUS  = request.POST['acierta_insured'],
            QUANTO  = request.POST['quanto_insured'],
            BONUS_MALUS  = request.POST['bm_insured'],
            EDAD_ASEGURADO  = request.POST['age_insured']
        )
        
        point = data['message'] = som_2.winner(test_val)
        
            # (29, 11)

        
    options = {
        'figsize':(7,7),
        'cmap': 'gray_r',
        'p_color': som_2.distance_map().T,
        'point': point 
    }

    chart = get_seftorganized_plot(options)
    data['chart'] = chart

    frequencies = load_frequencies()

    options = {
        'figsize':(7,7),
        'cmap': 'Blues',
        'p_color': frequencies.T,
        'point': point
    }

    chart_2 = get_seftorganized_plot(options)
    data['chart_2'] = chart_2

    return render(request, 'main_app/all_risk_1.html', data)


def all_risk_2(request):
    """
        View to generate HTML Template respose to URL <IP>:<PORT>/todo_riesgo/2
        @var request: HTTML REQUEST
    """
    if request.method == 'POST':
        scores = load_scores(request.POST['score'])
        
        return render(request, 'main_app/all_risk_2.html', {'scores' : scores['size'], 'data': scores['data'] })
    
    return render(request, 'main_app/all_risk_2.html')


def all_risk_3(request):
    """
        View to generate HTML Template respose to URL <IP>:<PORT>/todo_riesgo/3
        @var request: HTTML REQUEST
    """
    data = {'selects': get_webapp_parameters()}

    som_2 , frequencies = load_model_IT2()
    point = None
    threshold = data['threshold'] = 0.88
    weight = data['weight'] = 0.7

    if request.method == 'POST':
        if 'fillInfo' in request.POST or 'locatePoint' in request.POST:
            data['data_filled'] = 'yes'
            data['form_data'] = request.POST.copy()

            if 'fillInfo' in request.POST:
                print("Rellenar datos")
                
                client = {}

                if request.POST['id_cliente'] != '':
                    client = search_client(request.POST['id_cliente'])
                    if len(client) > 0:
                        front_client = all_risk_form_data(post = client, method='r')
                        for key, value in front_client.items():
                            data['form_data'][key] = value
                    
                
                if len(client) == 0:
                    data['message'] = CLIENT_NO_FOUND
                else:
                    data['message'] = CLIENT_FOUND
          

            if 'locatePoint' in request.POST:
                print("Localizar datos")
                pandas_form = all_risk_form_data(post = data['form_data'])
                toggles = ['TOMADOR_ASEGURADO_IGUAL_POLIZA','TOMADOR_ASEGURADO_IGUAL_SINIESTRO','MUNICIPIO_SINIESTRO_POLIZA_IGUAL']
                
                if 'SEXO_CONDUCTOR' in pandas_form:
                    pandas_form['SEXO_CONDUCTOR'] = 'M'
                else:
                    pandas_form['SEXO_CONDUCTOR'] = 'F'

                for toggle in toggles:
                    if toggle in pandas_form:
                        pandas_form[toggle] = '1'
                    else:
                        pandas_form[toggle] = '0'

                array_result = getDataForModel_IT2(**pandas_form)
                point = som_2.winner(array_result)
                data['message'] = POINT_CALCULATED.format(point)
            

        if 'thr_wei_button' in request.POST:
            print("Calcular umbral y peso")
            #for key, value in request.POST.items():
            #    print(key, '->', value)
            threshold = request.POST['threshold']
            weight = request.POST['weight_range']


    options = {
        'figsize':(7,7),
        'cmap': 'Purples',
        'p_color': som_2.distance_map().T,
        'point': point 
    }

    chart = get_seftorganized_plot(options)
    data['chart'] = chart

    options = {
        'figsize':(7,7),
        'cmap': 'Reds',
        'p_color': frequencies.T,
        'point': point
    }

    chart_2 = get_seftorganized_plot(options)
    data['chart_2'] = chart_2

    countX = 0
    countY = 0
    vec = []
    max = 0
    for x in frequencies:
        countY = 0
        for y in frequencies:
            vec.append([countX,countY,frequencies[countX][countY]])
            if max < frequencies[countX][countY]:
                max = frequencies[countX][countY]
            countY += 1
        countX += 1

    options = {
        'figsize':(7,7),
        'vec': vec,
        'point': point,
        'max': max
    }
    chart_3 = get_3d_freq_plot(options)
    data['chart_3'] = chart_3

    options = {
        'figsize':(7,7),
        'threshold': threshold,
        'weight': weight
    }
    chart_4 = get_threshold_hist_plot(options)
    data['chart_4'] = chart_4

    data['threshold'] = threshold
    data['weight'] = weight 
    data['thr_table'] = load_dataframe_weight(complete= False, threshold= threshold)

    return render(request, 'main_app/all_risk_3.html', data)


def all_risk_4(request):
    """
        View to generate HTML Template respose to URL <IP>:<PORT>/todo_riesgo/4
        @var request: HTTML REQUEST
    """
    data = {'selects': get_webapp_parameters()}
    if request.method == 'POST':
        if 'fillInfo' in request.POST or 'locatePoint' in request.POST:
            data['data_filled'] = 'yes'
            data['form_data'] = request.POST.copy()

            if 'fillInfo' in request.POST:

templates/main_app/all_risk_2.html
{% extends "main_app/base.html" %}

<!-- Inject code in block -->
{% block head_content %}
    <title> Todo Riesgo: Proyecto Fraude - Seguros Bolívar </title>
{% endblock %}

{% block container %}
    <h1> Seguros todo riesgo: 
        <small>Siniestros relacionados a puntaje </small>
    </h1>
    <section class="content">
        <div class="col-sm-6 col-lg-2">
            <div class="box">
                <div class="box-header with-border">
                    <i class="fa fa-line-chart"></i>
                    <h3 class="box-title">Puntaje</h3>
                </div>
                <div class="box-body">
                    <form method="POST" action="{% url 'all_risk:2' %}">               
                        {% csrf_token %}
                        <div class="form-group" >
                            <input type="number" class="form-control" id="score" name="score" step="0.01" placeholder="Ingresar">
                        </div>
                        <div class="form-group">
                            <button type="submit" 
                                class="btn btn-primary pull-right">
                                <i class="fa fa-cubes"></i> Consultar
                            </button>
                        </div>
                    </form>
                </div>
       
            </div>
        </div>
        <div class="col-sm-6 col-lg-10">
            <div class="box box-success">
                <div class="box-header with-border">
                    <i class="fa fa-ellipsis-h"></i>
                    <h3 class="box-title">Siniestros por puntaje</h3>
  
                    <div class="box-tools pull-right">
                      <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                              title="Ocultar/Mostrar">
                        <i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    {% if scores %}
                        <table id="scores_table" class="table table-bordered table-striped" >
                            <thead>
                                <th align="center">Póliza</th>
                                <th align="center">Departamento póliza</th>
                                <th align="center">Departamento siniestro</th>
                                <th align="center">Marca</th>
                                <th align="center">Línea</th>
                                <th align="center">Reclamos anteriores</th>
                                <th align="center">Valor Asegurado</th>
                                <th align="center">Incurrido</th>
                                
                            </thead>
                            <tbody>
                                {% for row in data %}
                                    <tr>
                                        <td>{{ row.NUMERO_SECUENCIA_POLIZA }}</td>
                                        <td>{{ row.DEPARTAMENTO_RIESGO }}</td>
                                        <td>{{ row.DEPARTAMENTO_SINIESTRO }}</td>
                                        <td>{{ row.MARCA_VEHICULO }}</td>
                                        <td>{{ row.LINEA }}</td>
                                        <td>{{ row.RECLAMOS_ANTERIORES }}</td>
                                        <td>{{ row.VALOR_ASEGURADO_VEHICULO }}</td>
                                        <td>{{ row.INCURRIDO }}</td>
                                       
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p>Digite un número de puntaje para recuperar la cantidad de siniestros con un número menor o igual al digitado. </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    {% if scores %}
        <script type="text/javascript">
            $(function () {
                $('#scores_table').DataTable()
            })
        </script>
    {% endif %}
{% endblock %}

templates/main_app/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <!-- Generate a Template Block to custom header in each .html file|  -->
        {% block head_content %} {% endblock %}
        
        <!-- Load static files (e.g css, js, etc) -->
        {% load static %}

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
        <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/skins/_all-skins.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap.min.css' %}">

        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'  %}">

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

        <script src="{% static 'js/jquery1.12.4.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/adminlte.min.js' %}"></script>
        <script src="{% static 'js/icheck.min.js' %}"></script>
        <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>

    </head>
    <body class="hold-transition skin-blue-light sidebar-mini">
        <div class="wrapper">
            
            {% include 'main_app/navbar.html' %}

            {% include 'main_app/menu.html' %}

            <div class="content-wrapper">
                <section class="content-header">
                    {% block container %}
                    {% endblock%}
                </section>
            </div>   
        </div>    
    </body>
</html>

templates/main_app/index.html
{% extends "main_app/base.html" %}

<!-- Inject code in block -->
{% block head_content %}
    <title> Home: Proyecto Fraude - Seguros Bolívar </title>
{% endblock %}

{% block container %}
    {% load static %}
    <h1> Proyecto Fraude - Seguros Bolívar </h1>
    <section class="content">
        <!--ROW 1: Collapse with SaaS description -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class= "box-title"><i class="fa fa-tag"></i>   Información general </h3>
                    </div>
                    <div class="box-body">
                        <div class="box-group" id="accordion">
                            <div class="panel box box-primary">
                                <div class="box-header with-border">
                                    <h4 class="box-title">
                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                            Proyecto
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseOne" class="panel-collapse collapse in">
                                    <div class="box-body">
                                        <dl>
                                            <dd>
                                                <b>Estudio de la viabilidad del uso de técnicas de aprendizaje 
                                                    automático para la detección de fraudes en pólizas de 
                                                    seguros de vehículos</b> 
                                            </dd>
                                            <br />

                                            <dd>
                                                Este sitio web es la interfaz para mostrar los resultados del proyecto que consiste en una prueba de concepto para el área de analítica 
                                                Banca Seguros de la empresa Seguros Bolívar, con el fin de determinar la viabilidad de usar técnicas de aprendizaje automático (ML) 
                                                en la detección de reclamaciones sospechosas de fraude en pólizas de seguros de vehículos todo riesgo y SOAT. 
                                            </dd>
                                            
                                            <br />

                                            <dd>
                                                Esta prueba de concepto tendrá como alcance las pólizas y reclamaciones realizadas en el territorio de Colombia para beneficiarios de Seguros Bolívar. 
                                            </dd>
                                            <br />
                                            
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <dt>Los componentes de esta funcionalidad son: </dt>
                                                    <img src="{% static 'img/Tech.png' %}" class="fit_chart_2">
                                                    
                                                </div>
                                            </div>
                                            
                                        </dl>
                                    </div>
                                </div>
                            </div>
                            <div class="panel box box-success">
                                <div class="box-header with-boder">
                                    <h4 class="box-title">
                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                                            Funcionalidades
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseTwo" class="panel-collapse collapse">
                                    <div class="box-body">
                                        <dd>
                                            <ul style="list-style-type: square;">
                                                <li><strong>Seguros Todo Riesgo: </strong> Mapas Autoorganizados</li>
                                                <li><strong>Seguros Todo Riesgo: </strong> Exploración de siniestros por puntaje </li>
                                                <li><strong>Seguros SOAT: </strong> Exploración de clusters de SOAT</li>
                                            </ul>
                                        </dd>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- END ROW 1 -->
    </section>
{% endblock %}

templates/main_app/menu.html
{% load static %}

<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">Menú Navegación</li>
            <li>
                <a href="{% url 'home:home' %}">
                  <i class="fa fa-mouse-pointer"></i> <span>Inicio</span>
                </a>
            </li>
            <li class="active treeview">
                <a href="#">
                  <i class="fa fa-car"></i> <span>Seguros Todo Riesgo</span>
                  <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                  </span>
                </a>
                <ul class="treeview-menu">
                  <!--
                  <li><a href="{% url 'all_risk:1' %}"><i class="fa fa-map-o"></i> Self-Organizing maps </a></li>
                  <li><a href="{% url 'all_risk:2' %}"><i class="fa fa-table"></i> Siniestro vs puntaje </a></li>
                  -->
                  <li><a href="{% url 'all_risk:4' %}"><i class="fa fa-map-o"></i>Menú Operador </a></li>
                  <li><a href="{% url 'all_risk:3' %}"><i class="fa fa-table"></i>Menú Analista </a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                  <i class="fa fa-ambulance"></i>
                  <span>Seguros SOAT</span>
                  <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                  </span>
                </a>
                <ul class="treeview-menu">
                  <!--
                  <li><a href="{% url 'soat:s1' %}"><i class="fa fa-credit-card"></i> Resultado Clustering </a></li>
                  -->
                  <li><a href="{% url 'soat:s2' %}"><i class="fa fa-credit-card"></i>Clustering SOAT </a></li>
                </ul>
            </li>
        </ul>
    </section>
</aside>

templates/main_app/navbar.html
{% load static %}

<header class="main-header">
    <!-- Logo -->
    <a herf="{% url 'home:home' %}" class="logo">
        <span class="logo-mini"><b>M</b>PF</span>
        <span class="logo-lg"><b>MINE </b> Proyecto Final</span>
    </a>
    
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{% static 'img/default-profile.png' %}" class="user-image" alt="User Image">
                        <span class="hidden-xs">Visitante</span>
                    </a>
                    <ul class="dropdown-menu">

                        <li class="user-header">
                            <img src="{% static 'img/default-profile.png' %}" class="img-circle" alt="User Image">
                            <p>Usuario visitante</p>
                        </li>

                        <li class="user-footer">
                            <div class="pull-right">
                                <a href="{% url 'home:home' %}" class="btn btn-default btn-flat">Salir</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>